"""Initial migration

Revision ID: 363038722684
Revises: 
Create Date: 2024-08-28 18:48:23.174498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '363038722684'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipo_accesorio',
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('accesorio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accesorio_id'], ['accesorio.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ),
    sa.PrimaryKeyConstraint('equipo_id', 'accesorio_id')
    )
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('accesorios_id')
        batch_op.drop_column('proveedor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('accesorios_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    op.drop_table('equipo_accesorio')
    op.drop_table('user')
    # ### end Alembic commands ###
