"""add models user

Revision ID: 74fe4e0610fb
Revises: 
Create Date: 2024-10-25 17:39:51.836465

"""
from werkzeug.security import generate_password_hash
from models import User
from app import db

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fe4e0610fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    existings_users = User.query.filter_by(username='admin').first()
    
    if not existings_users:
        admin_user = User(
            username='admin',
            password_hash=generate_password_hash('admin'),
            is_admin=True,
        )
        db.session.add(admin_user)
        db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
