"""accesorio

Revision ID: 9e8304c54d97
Revises: 363038722684
Create Date: 2024-08-28 23:36:34.155099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e8304c54d97'
down_revision = '363038722684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo_accesorio', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'accesorio', ['accesorio_id'], ['id'])

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('ubicacion',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('ubicacion',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('equipo_accesorio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
