"""empty message

Revision ID: c7eadcc729cc
Revises: e2c93cfb78ae
Create Date: 2024-07-03 22:59:19.655163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7eadcc729cc'
down_revision = 'e2c93cfb78ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'proveedor', ['proveedor_id'], ['id'])

    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'equipo', ['equipo_id'], ['id'])

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('marca_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'marca', ['marca_id'], ['id'])
        batch_op.create_foreign_key(None, 'stock', ['stock_id'], ['id'])

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_constraint('modelo_ibfk_2', type_='foreignkey')
        batch_op.drop_column('marca_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('modelo_ibfk_2', 'marca', ['marca_id'], ['id'])

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('marca_id')
        batch_op.drop_column('stock_id')

    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipo_id')

    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proveedor_id')

    # ### end Alembic commands ###
